CrackMe02 : CrackMe02.c
	clang -o ../../build/crackme02/CrackMe02 CrackMe02.c
	x86_64-pc-linux-gnu-gcc -o ../../build/crackme02/CrackMe02.exe CrackMe02.c
clean :
		rm -f ../../build/crackme02/CrackMe02
		rm -f ../../build/crackme02/CrackMe02.exe

