pe001 : CrackMe01.c
	gcc -o ../../build/crackme01/CrackMe01 CrackMe01.c
	x86_64-pc-linux-gnu-gcc -o ../../build/crackme01/CrackMe01.exe CrackMe01.c
clean :
		rm -f ../../build/crackme01/CrackMe01
		rm -f ../../build/crackme01/CrackMe01.exe

